import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  wrap: { flexGrow: 1, backgroundColor: '#fff', padding: 28, gap: 12 },
  center: { flex: 1, backgroundColor: '#fff', padding: 28, justifyContent: 'center', gap: 12 },
  kicker: { fontSize: 13, color: '#6C5CE7', fontWeight: '700', letterSpacing: 1 },
  title: { fontSize: 28, fontWeight: '800', color: '#2D3436' },
  sub: { fontSize: 15, color: '#636E72', marginBottom: 8, lineHeight: 22 },
  body: { fontSize: 16, color: '#636E72', lineHeight: 22 },
  input: { borderWidth: 1, borderColor: '#DFE6E9', borderRadius: 12, padding: 14, fontSize: 16 },
  button: { backgroundColor: '#6C5CE7', borderRadius: 12, padding: 16, alignItems: 'center' },
  buttonText: { color: '#fff', fontWeight: '700', fontSize: 16 },
  buttonGhost: {
    borderWidth: 1,
    borderColor: '#DFE6E9',
    borderRadius: 12,
    padding: 14,
    alignItems: 'center',
  },
  buttonGhostText: { color: '#2D3436', fontWeight: '600', fontSize: 15 },
  link: { fontSize: 16, color: '#6C5CE7', fontWeight: '600' },
  error: { color: '#E74C3C' },
  notice: { color: '#00B894' },
  row: { borderBottomWidth: 1, borderBottomColor: '#F1F2F6', paddingVertical: 12, gap: 4 },
  name: { fontSize: 16, fontWeight: '600', color: '#2D3436' },
  meta: { fontSize: 13, color: '#636E72' },
  chip: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 10,
    backgroundColor: '#F3F0FF',
  },
  chipText: { fontSize: 12, fontWeight: '700', color: '#6C5CE7' },
  actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 6 },
  action: { fontSize: 14, color: '#6C5CE7', fontWeight: '600' },
  actionDanger: { fontSize: 14, color: '#E74C3C', fontWeight: '600' },
  card: {
    borderWidth: 1,
    borderColor: '#F1F2F6',
    borderRadius: 12,
    padding: 14,
    gap: 6,
  },
  section: { fontSize: 18, fontWeight: '700', color: '#2D3436', marginTop: 8 },
});
